[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fed_xgboost_aml"
version = "1.0.0"
description = "Federated Learning with XGBoost and Flower (AML)"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.22.0",
    "xgboost>=2.0.0",
    "numpy>=1.21.0",
    "scikit-learn>=1.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "RichardMuscat"

[tool.flwr.app.components]
serverapp = "server_app:app"
clientapp = "client_app:app"

[tool.flwr.app.config]
num-server-rounds = 20
fraction-train = 1.0
fraction-evaluate = 1.0
# local-epochs = 185
local-epochs = 500    # small_optimized

# run config
run-tag = "client_upsampling_mean_params"  # e.g., "client_upsampling_centralized", "client_upsampling_federated", "client_specific_upsampling_centralized"


# Imbalance handling: ADASYN
imbalance-strategy = "adasyn"
sampling-strategy = 0

# XGBoost parameters (from Altman et al.)
# params.objective = "binary:logistic"
# params.eta = 0.09                    # Learning rate
# params.max-depth = 10
# params.reg-lambda = 82.0
# params.colsample-bytree = 0.8
# params.subsample = 0.8
# params.tree-method = "hist"
# params.eval-metric = "auc"
# params.nthread = 16
# params.scale-pos-weight = 4.5


# #XGBoost parameters - Small Optimized Median
# params.objective = "binary:logistic"
# params.eta = 0.0751
# params.max-depth = 10
# params.reg-lambda = 1.3373
# params.colsample-bytree = 0.8233
# params.subsample = 0.8000
# params.min-child-weight = 5
# params.gamma = 1.1378
# params.tree-method = "hist"
# params.eval-metric = "auc"
# params.seed = 42
# params.nthread = 16


# XGBoost parameters - Small Optimized Mean
params.objective = "binary:logistic"
params.eta = 0.0720
params.max-depth = 11
params.reg-lambda = 17.6
params.colsample-bytree = 0.8386
params.subsample = 0.7728
params.min-child-weight = 6
params.gamma = 0.7622
params.tree-method = "hist"
params.eval-metric = "auc"
params.seed = 42
params.nthread = 16


[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 5          # number of banks

